# <termo de pesquisa> | <tecto em EUR> | <regra do título>
# Regras de título:
#   palavra1+palavra2  => tem de ter palavra1 E palavra2
#   -palavra3         => NÃO pode ter palavra3
#   exemplo: optiplex+3070-aio-ecra-monitor

# Critério 1: Dell Optiplex 3070 < 90€
dell optiplex 3070 | 95 | optiplex+3070-aio-ecra-monitor-cabo-cable-pecas-peca-caddy-fonte-alimentation-alimentatore-alimentador-chargeur-charger-carregador-part-parte-bateria-battery-placa-carte-board

# Critério 2: Dell Optiplex 308x < 150€
dell optiplex 3080 | 150 | optiplex+3080-aio-ecra-monitor-cabo-cable-pecas-peca-caddy-fonte-alimentation-alimentatore-alimentador-chargeur-charger-carregador-part-parte-bateria-battery-placa-carte-board
dell optiplex 3085 | 150 | optiplex+3085-aio-ecra-monitor-cabo-cable-pecas-peca-caddy-fonte-alimentation-alimentatore-alimentador-chargeur-charger-carregador-part-parte-bateria-battery-placa-carte-board

# Critério 3: Dell Optiplex 309x < 200€
dell optiplex 3090 | 200 | optiplex+3090-aio-ecra-monitor-cabo-cable-pecas-peca-caddy-fonte-alimentation-alimentatore-alimentador-chargeur-charger-carregador-part-parte-bateria-battery-placa-carte-board

dell optiplex 3020 | 30 | optiplex+3020-aio-ecra-monitor-cabo-cable-pecas-peca-caddy-fonte-alimentation-alimentatore-alimentador-chargeur-charger-carregador-part-parte-bateria-battery-placa-carte-board

dell optiflex 3020 | 26 | optiplex+3020-aio-ecra-monitor-cabo-cable-pecas-peca-caddy-fonte-alimentation-alimentatore-alimentador-chargeur-charger-carregador-part-parte-bateria-battery-placa-carte-board

dell optiflex 3000 | 260 | optiplex+3000-aio-ecra-monitor-cabo-cable-pecas-peca-caddy-fonte-alimentation-alimentatore-alimentador-chargeur-charger-carregador-part-parte-bateria-battery-placa-carte-board
